version: 2.0

jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/pietvanzoen.com
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/pietvanzoen.com

  bundle:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/pietvanzoen.com
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/pietvanzoen.com/vendor/bundle

  build:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/pietvanzoen.com
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run:
          name: Build site
          command: bundle exec middleman build
      - save_cache:
          key: v1-site-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/pietvanzoen.com/build

  test:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/pietvanzoen.com
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle --path vendor/bundle
      - run:
          name: Run tests
          run: bundle exec ruby test.rb

  deploy:
    branches:
      only:
        - master
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/pietvanzoen.com
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: cp -r .config ./source
      - run:
          name: Configure github user
          command: |
            git config user.email $GIT_USER_EMAIL
            git config user.name $GIT_USER_NAME
      - bundle exec middleman deploy

workflows:
  version: 2
  build-and-deploy:
    branches:
      ignore:
        - gh-pages
    jobs:
      - checkout_code
      - bundle:
          requires:
            - checkout_code
      - build:
          requires:
            - bundle
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
            - build

